### PR TITLE
Hotfix/require jsdoc

### PR DESCRIPTION
**Pull request by bizob2828**
We try to make sure functions are doc'd and with accurate syntax but this is def a mixed bag.  I think it is good for us to have these rules in place. It definitely helps with new hires or people new to the code.  Since most repos have switch to only linting on staged commits this will be a work in progress.

I also am excluding some of our linting rules in tests as we got burned on max params and func names before

### CODE REVIEW

**Comment by ewandennis** [comment]
If we're serious about this, we should also resolve these jsdoc issues. A _lot_ of our most interesting code passes objects around and returns promises.

**Anonymous Objects**
`@param {Object} opts` - `Object` tells me nothing
`@param {Object.<String, Number>} numsNText` still not great
`@param {{makeMeRich: Boolean, howRich: Number}}` yay!

**Anonymous Promises**
`@returns {Promise}` - :(
`@returns {Promise.<Object>}` - :((
`@returns {Promise.<{moneyPlz: Boolean, yesAllOfIt: Boolean}>}` yay

**Comment by bizob2828** [comment]
I'd love for someone to flesh this out more. having accurate, comprehensive docs would be great. I know it got into a typescript debate offline not sure if we are all ready for that

**Comment by tough-griff** [comment]
@bizob2828 see #16, which @beardyman has already merged down.

**Comment by bizob2828** [comment]
right but my PR is essentially a clone of that but just for all

**Pull request closed without merging**
